server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    gzip on;
    location / { try_files $uri /index.html; }
    location /api/ { proxy_pass http://backend-svc.kubevision.svc.cluster.local:3001; }
}
